# Generated by Django 4.2.7 on 2023-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='texto',
        ),
        migrations.AddField(
            model_name='dado',
            name='email',
            field=models.EmailField(auto_created=True, default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dado',
            name='mensagem',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='dado',
            name='usuario',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
