# Generated by Django 4.2.7 on 2023-12-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_remove_dado_texto_dado_email_dado_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='dado',
            name='mensagem',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='dado',
            name='usuario',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
