# Generated by Django 4.2.7 on 2023-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_dado_email_alter_dado_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='dado',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dado',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
