# Generated by Django 4.2.7 on 2023-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_dado_email_alter_dado_mensagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dado',
        ),
    ]
