# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_dadosformulario_delete_dado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosformulario',
            name='campo1',
        ),
        migrations.RemoveField(
            model_name='dadosformulario',
            name='campo2',
        ),
        migrations.AddField(
            model_name='dadosformulario',
            name='campo_email',
            field=models.EmailField(auto_created=True, default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='dadosformulario',
            name='campo_usuario',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
