# Generated by Django 4.2.7 on 2023-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_rename_campo_email_dadosformulario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosformulario',
            name='senha',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
